name: Build NativeScript Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: project

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install NativeScript CLI
        run: npm install -g @nativescript/cli

      - name: Install Project Dependencies
        run: npm install

      - name: Build APK (Debug)
        run: ns build android --no-watch

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: camera-spoofer-debug-apk
          path: project/platforms/android/app/build/outputs/apk/debug/*.apk
