name: Build NativeScript Android APK

on:
  push:
    branches:
      - main

jobs:
  Build-APK:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install NativeScript CLI
        run: npm install -g @nativescript/cli

      - name: Install dependencies
        run: npm install

      - name: Add Android platform (if not already added)
        run: ns platform add android || echo "Platform already added"

      - name: Build Android APK (release)
        run: ns build android --release --no-sign

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: camera-spoofer-apk
          path: platforms/android/app/build/outputs/**/*.apk
